NHSDigital/immunisation-batch

- azure/azure-pr-pipeline.yml
- azure/project.yml
>  AMB-0001-test-pipelines

- .github/workflows/continuous-disintegration.yml
- azure/project.yml
- terraform/batch_processing.tf
- terraform/outputs.tf
- terraform/policies/s3_batch.json
- terraform/policies/s3_batch_policy.json
- terraform/policies/s3_batch_policy_prod.json
- terraform/policies/s3_batch_prod.json
> AMB-0004-PR-Teardown

- batch/src/router_lambda_function.py
- batch/tests/test_lambda_e2e.py
- batch/tests/test_router_lambda_function.py
- terraform/lambda_batch.tf
> Added KMS decryption in terraform script

- azure/azure-release-pipeline.yml
> Created release structure

- azure/azure-release-pipeline.yml
> Fix release INT env

- terraform/batch_processing.tf
> Fix KMS key issue

- terraform/batch_processing.tf
> Fix release pipeline

- manifest_template.yml
> Fix INT release pipeline

- azure/templates/post-deploy.yml
- terraform/Makefile
- terraform/outputs.tf
- terraform/route53.tf
- terraform/variables.tf
> AMB-2201-Fix-release-pipeline-for-INT

- azure/azure-release-pipeline.yml
> Fix-Release-Pipeline-for-REF

- filenameprocessor/src/router_lambda_function.py
- filenameprocessor/tests/test_lambda_e2e.py
- filenameprocessor/tests/test_router_lambda_function.py
- recordforwarder/src/forwarding_lambda.py
- recordforwarder/tests/test_e2e_forwarding_lambda.py
- recordforwarder/tests/test_forwarding_lambda.py
- recordprocessor/src/processing_lambda.py
- recordprocessor/tests/test_lambda_e2e.py
- terraform/batch_processing.tf
- terraform/forwarder_lambda.tf
- terraform/lambda_batch.tf
- terraform/permissions_config.tf
- terraform/processor_lambda.tf
> Renamed the object names

- .github/workflows/continuous-disintegration.yml
- azure/azure-pr-teardown-pipeline.yml
> Teardown pipeline with Service principals implementation

- .github/workflows/continuous-disintegration.yml
- azure/azure-pr-teardown-pipeline.yml
> Amb 0004 fix azure login for service principal

- .github/workflows/continuous-disintegration.yml
- azure/azure-pr-teardown-pipeline.yml
Reverts NHSDigital/immunisation-batch#41
> Revert "Amb 0004 fix azure login for service principal"

- azure/azure-pr-teardown-pipeline.yml
> Test Teardown pipeline

- scripts/destroy_unused_workspaces.py
> AMB-0008 Teardown with SP

- azure/azure-pr-teardown-pipeline.yml
> TEst service principals

- .github/workflows/continuous-disintegration.yml
> AMB-0009-Use-PAT-for-teardown

- .github/workflows/continuous-disintegration.yml
> Service Principal code changes

- filenameprocessor/src/__init__.py
- filenameprocessor/src/initial_file_validation.py
- filenameprocessor/src/make_and_upload_ack_file.py
- filenameprocessor/src/router_lambda_function.py
- filenameprocessor/src/send_sqs_message.py
- filenameprocessor/src/utils_for_filenameprocessor.py
- filenameprocessor/tests/test_initial_file_validation.py
- filenameprocessor/tests/test_lambda_e2e.py
- filenameprocessor/tests/test_send_sqs_message.py
> AMB-2261 : BUG - imports not working

- azure/templates/build.yml
- recordforwarder/tests/test_e2e_forwarding_lambda.py
- recordforwarder/tests/test_forwarding_lambda.py
- recordprocessor/src/batch_processing.py
- recordprocessor/tests/test_lambda_e2e.py
- recordprocessor/tests/test_processing_lambda.py
> Amb 2262 bug tests failing

- filenameprocessor/src/initial_file_validation.py
- filenameprocessor/src/make_and_upload_ack_file.py
- filenameprocessor/tests/test_initial_file_validation.py
- filenameprocessor/tests/utils_for_tests/values_for_tests.py
- recordforwarder/src/forwarding_lambda.py
- recordforwarder/tests/test_e2e_forwarding_lambda.py
- recordforwarder/tests/test_forwarding_lambda.py
- recordprocessor/src/batch_processing.py
- recordprocessor/tests/test_lambda_e2e.py
- terraform/ecs_batch_processor_config.tf
- terraform/file_name_processor.tf
- terraform/forwarder_lambda.tf
- terraform/permissions_config.tf
- terraform/s3_config.tf
> AMB-0009-Few-more-changes-for-account-integration

- terraform/Makefile
> AMB-0009-Pipeline-Improvements

- azure/templates/deploy-stage.yml
> AMB-0009-Naming corrections

- terraform/variables.tf
> AMB - 2249 - Terraform changes

- infra/endpoints.tf
- infra/kinesis_role.tf
- infra/kms_kinesis.tf
- infra/kms_lambda.tf
- infra/kms_s3.tf
- terraform/ecs_batch_processor_config.tf
- terraform/file_name_processor.tf
- terraform/forwarder_lambda.tf
- terraform/kinesis_config.tf
- terraform/variables.tf
> AMB-2292-Pentesters fixes B

- azure/azure-pr-pipeline.yml
- azure/templates/deploy-manual-approval.yml
- azure/templates/deploy-stage.yml
- azure/templates/deploy-stages.yml
- azure/templates/post-deploy.yml
> AMB-0008-Production-preperation
